branch-defaults:
  master:
    environment: addcurio-env
environment-defaults:
  addcurio-env:
    branch: null
    repository: null
global:
  application_name: addcurio
  default_ec2_keyname: addcurio-prod
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/PHP 7.3 running on
    64bit Amazon Linux/2.9.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
